# Generated by Django 3.2 on 2021-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210503_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='audiobooks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=' ', max_length=100)),
                ('author', models.CharField(default=' ', max_length=100)),
                ('narrator', models.CharField(default=' ', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField()),
                ('host', models.CharField(default=' ', max_length=100)),
                ('participants', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
