# Generated by Django 3.2 on 2021-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210505_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='audiobooks',
            new_name='audiobook',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.CharField(blank=True, default=' ', max_length=111),
        ),
    ]
