# Generated by Django 3.2 on 2021-05-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210505_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audiobook',
        ),
    ]
